import std/[json, options, os, osproc, strutils]

import ./diagnostics
import ./model
import ./render_js
import ./render_package
import ./validate

const
  TreeNimphJsHeader* = "// Generated by TreeNimph — do not edit manually."
  TreeNimphScmHeader* = "; Generated by TreeNimph — do not edit manually."

proc isTreeNimphOwned(path: string, header: string): bool =
  if not fileExists(path):
    return false
  let content = readFile(path)
  content.startsWith(header)

proc isTreeNimphPackageJson(path: string, grammarName: string): bool =
  if not fileExists(path):
    return false
  try:
    let j = parseJson(readFile(path))
    j["name"].getStr() == "tree-sitter-" & grammarName
  except:
    false

proc isTreeNimphTreeSitterJson(path: string, grammarName: string): bool =
  if not fileExists(path):
    return false
  try:
    let j = parseJson(readFile(path))
    j["grammars"][0]["name"].getStr() == grammarName
  except:
    false

proc safeWrite(path: string, content: string, canOverwrite: bool, ownershipCheck: proc(): bool) =
  if fileExists(path):
    if not canOverwrite:
      raise newException(ExportError, "File already exists and overwrite is disabled: " & path)
    if not ownershipCheck():
      raise newException(ExportError, "Refusing to overwrite file not generated by TreeNimph: " & path)
  writeFile(path, content)

proc writeQueryFile(path: string, content: Option[string], writeStubs: bool, overwrite: bool) =
  if content.isSome:
    writeFile(path, content.get)
  elif writeStubs:
    if fileExists(path):
      if not overwrite:
        return
      if not isTreeNimphOwned(path, TreeNimphScmHeader):
        return
    writeFile(path, TreeNimphScmHeader & "\n")

proc exportGrammar*(g: Grammar, config: ExportConfig) =
  g.validateOrRaise()

  let outDir = config.outDir
  let queriesDir = outDir / "queries"
  let srcDir = outDir / "src"

  createDir(outDir)
  createDir(queriesDir)
  createDir(srcDir)

  let grammarJsContent = g.renderGrammarJs()
  let grammarJsPath = outDir / "grammar.js"
  safeWrite(grammarJsPath, grammarJsContent, config.overwrite,
    proc(): bool = isTreeNimphOwned(grammarJsPath, TreeNimphJsHeader))

  let packageJsonContent = g.renderPackageJson()
  let packageJsonPath = outDir / "package.json"
  safeWrite(packageJsonPath, packageJsonContent, config.overwrite,
    proc(): bool = isTreeNimphPackageJson(packageJsonPath, g.name))

  let writeStubs = config.writeQueryStubs
  let treeSitterJsonContent = g.renderTreeSitterJson(g.queryFiles, writeStubs)
  let treeSitterJsonPath = outDir / "tree-sitter.json"
  safeWrite(treeSitterJsonPath, treeSitterJsonContent, config.overwrite,
    proc(): bool = isTreeNimphTreeSitterJson(treeSitterJsonPath, g.name))

  let qf = if g.queryFiles.isSome: g.queryFiles.get else: QueryFiles()
  writeQueryFile(queriesDir / "highlights.scm", qf.highlights, writeStubs, config.overwrite)
  writeQueryFile(queriesDir / "locals.scm", qf.locals, writeStubs, config.overwrite)
  writeQueryFile(queriesDir / "injections.scm", qf.injections, writeStubs, config.overwrite)
  writeQueryFile(queriesDir / "tags.scm", qf.tags, writeStubs, config.overwrite)

  if g.scannerPath.isSome:
    copyFile(g.scannerPath.get, srcDir / "scanner.c")

  if config.runGenerate:
    let (output, exitCode) = execCmdEx("tree-sitter generate", workingDir = outDir)
    if exitCode != 0:
      raise newException(ExportError,
        "tree-sitter generate failed (exit code " & $exitCode & "):\n" & output)
    if not fileExists(srcDir / "parser.c"):
      raise newException(ExportError,
        "tree-sitter generate succeeded but src/parser.c was not created")
