import std/[options, sequtils, strutils]

import ./diagnostics
import ./model

proc escapeJsSingleQuote(s: string): string =
  result = ""
  for c in s:
    case c
    of '\\':
      result.add "\\\\"
    of '\'':
      result.add "\\'"
    of '\n':
      result.add "\\n"
    of '\r':
      result.add "\\r"
    of '\t':
      result.add "\\t"
    else:
      result.add c

proc escapeRegexSlash(pattern: string): string =
  result = ""
  var i = 0
  while i < pattern.len:
    if pattern[i] == '\\' and i + 1 < pattern.len:
      result.add pattern[i]
      result.add pattern[i + 1]
      i += 2
    elif pattern[i] == '/':
      result.add "\\/"
      inc i
    else:
      result.add pattern[i]
      inc i

proc indent(level: int): string =
  repeat(' ', level * 2)

proc indentMultiline(s: string, level: int): string =
  let lines = s.split('\n')
  if lines.len <= 1:
    return s
  let ind = indent(level)
  result = lines[0]
  for i in 1..<lines.len:
    result.add "\n" & ind & lines[i]

proc renderExpr(e: Expr, indentLevel: int): string

proc renderCallExpr(funcName: string, items: seq[Expr], indentLevel: int): string =
  let renderedItems = items.mapIt(renderExpr(it, indentLevel + 1))
  let singleLine = funcName & "(" & renderedItems.join(", ") & ")"
  let currentIndent = indent(indentLevel).len

  if renderedItems.allIt(not it.contains('\n')) and currentIndent + singleLine.len <= 80:
    return singleLine

  let innerIndent = indent(indentLevel + 1)
  result = funcName & "(\n"
  for item in renderedItems:
    result.add innerIndent & indentMultiline(item, indentLevel + 1) & ",\n"
  result.add indent(indentLevel) & ")"

proc renderWrapExpr(funcName: string, child: Expr, indentLevel: int): string =
  let rendered = renderExpr(child, indentLevel + 1)
  let singleLine = funcName & "(" & rendered & ")"
  let currentIndent = indent(indentLevel).len

  if not rendered.contains('\n') and currentIndent + singleLine.len <= 80:
    return singleLine

  let innerIndent = indent(indentLevel + 1)
  result = funcName & "(\n"
  result.add innerIndent & indentMultiline(rendered, indentLevel + 1) & ",\n"
  result.add indent(indentLevel) & ")"

proc renderFieldExpr(e: Expr, indentLevel: int): string =
  let childRendered = renderExpr(e.fieldExpr, indentLevel + 1)
  let singleLine = "field('" & escapeJsSingleQuote(e.fieldName) & "', " & childRendered & ")"
  let currentIndent = indent(indentLevel).len

  if not childRendered.contains('\n') and currentIndent + singleLine.len <= 80:
    return singleLine

  "field('" & escapeJsSingleQuote(e.fieldName) & "', " &
    indentMultiline(childRendered, indentLevel + 1) & ")"

proc renderAliasExpr(e: Expr, indentLevel: int): string =
  let childRendered = renderExpr(e.aliasExpr, indentLevel + 1)
  let nameRendered =
    if e.aliasNamed:
      "$." & e.aliasName
    else:
      "'" & escapeJsSingleQuote(e.aliasName) & "'"
  "alias(" & childRendered & ", " & nameRendered & ")"

proc renderPrecExpr(e: Expr, indentLevel: int): string =
  let funcName = case e.precAssoc
  of assocNone:
    "prec"
  of assocLeft:
    "prec.left"
  of assocRight:
    "prec.right"
  of assocDynamic:
    "prec.dynamic"

  let childRendered = renderExpr(e.precExpr, indentLevel + 1)
  let singleLine = funcName & "(" & $e.precLevel & ", " & childRendered & ")"
  let currentIndent = indent(indentLevel).len

  if not childRendered.contains('\n') and currentIndent + singleLine.len <= 80:
    return singleLine

  funcName & "(" & $e.precLevel & ", " & indentMultiline(childRendered, indentLevel + 1) & ")"

proc renderExpr(e: Expr, indentLevel: int): string =
  case e.kind
  of ekRef:
    "$." & e.refName
  of ekText:
    "'" & escapeJsSingleQuote(e.textValue) & "'"
  of ekRegex:
    "/" & escapeRegexSlash(e.regexPattern) & "/"
  of ekBlank:
    "blank()"
  of ekSequence:
    renderCallExpr("seq", e.items, indentLevel)
  of ekChoice:
    renderCallExpr("choice", e.items, indentLevel)
  of ekOptional:
    renderWrapExpr("optional", e.item, indentLevel)
  of ekZeroOrMore:
    renderWrapExpr("repeat", e.item, indentLevel)
  of ekOneOrMore:
    renderWrapExpr("repeat1", e.item, indentLevel)
  of ekField:
    renderFieldExpr(e, indentLevel)
  of ekAlias:
    renderAliasExpr(e, indentLevel)
  of ekToken:
    renderWrapExpr("token", e.tokenExpr, indentLevel)
  of ekImmediateToken:
    renderWrapExpr("token.immediate", e.tokenExpr, indentLevel)
  of ekPrecedence:
    renderPrecExpr(e, indentLevel)

proc renderGrammarJs*(g: Grammar): string =
  ## Renders the grammar as a Tree-sitter grammar.js file.
  ## The grammar must be valid — call validate() or validateOrRaise() first.
  ## Passing a grammar with nil rule bodies will raise an AssertionDefect.
  for i, rule in g.rules:
    assert rule.body != nil, "Rule \"" & rule.canonicalName &
      "\" (rule #" & $(i + 1) & ") has a nil body — did you forget to call validateOrRaise()?"
  result = "// Generated by TreeNimph — do not edit manually.\n\n"
  result.add "module.exports = grammar({\n"
  result.add "  name: '" & g.name & "',\n"

  if g.word.isSome:
    result.add "\n  word: $ => $." & g.word.get & ",\n"

  if g.extras.len > 0:
    result.add "\n  extras: $ => [\n"
    for e in g.extras:
      result.add "    " & renderExpr(e, 2) & ",\n"
    result.add "  ],\n"

  if g.supertypes.len > 0:
    result.add "\n  supertypes: $ => [\n"
    for name in g.supertypes:
      result.add "    $." & name & ",\n"
    result.add "  ],\n"

  if g.inline.len > 0:
    result.add "\n  inline: $ => [\n"
    for name in g.inline:
      result.add "    $." & name & ",\n"
    result.add "  ],\n"

  if g.conflicts.len > 0:
    result.add "\n  conflicts: $ => [\n"
    for conflict in g.conflicts:
      result.add "    [" & conflict.mapIt("$." & it).join(", ") & "],\n"
    result.add "  ],\n"

  if g.externals.len > 0:
    result.add "\n  externals: $ => [\n"
    for e in g.externals:
      result.add "    " & renderExpr(e, 2) & ",\n"
    result.add "  ],\n"

  result.add "\n  rules: {\n"
  for i, rule in g.rules:
    let cname = rule.canonicalName
    let bodyRendered = renderExpr(rule.body, 2)

    if i > 0:
      result.add "\n"

    if not bodyRendered.contains('\n'):
      result.add "    " & cname & ": $ => " & bodyRendered & ",\n"
    else:
      result.add "    " & cname & ": $ => " & indentMultiline(bodyRendered, 2) & ",\n"

  result.add "  }\n"
  result.add "});\n"
