// Generated by TreeNimph — do not edit manually.

module.exports = grammar({
  name: 'json_like',

  extras: $ => [
    /\s+/,
  ],

  rules: {
    document: $ => $._value,

    _value: $ => choice($.object, $.array, $.string, $.number, $.true, $.false, $.null),

    object: $ => seq(
          '{',
          optional(seq($.pair, repeat(seq(',', $.pair)), optional(','))),
          '}',
        ),

    pair: $ => seq(field('key', $.string), ':', field('value', $._value)),

    array: $ => seq(
          '[',
          optional(seq($._value, repeat(seq(',', $._value)), optional(','))),
          ']',
        ),

    string: $ => /"[^"]*"/,

    number: $ => /[0-9]+/,

    true: $ => 'true',

    false: $ => 'false',

    null: $ => 'null',
  }
});
